[build]
  publish = "."
  command = "cd .. && mv repo bento && cd bento && HUGO_BASEURL=https://bento-hugo-theme.netlify.app/ yarn build:example && cp -r exampleSite/public ../repo"
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  NODE_VERSION = "12.16.2"

[context.deploy-preview]
  command = "cd .. && mv repo bento && cd bento && HUGO_BASEURL=$DEPLOY_PRIME_URL yarn build:example && cp -r exampleSite/public ../repo"

[context.deploy-preview.environment]
  HUGO_GOOGLEANALYTICS = "dev"

[context.branch-deploy]
  command = "cd .. && mv repo bento && cd bento && HUGO_BASEURL=$DEPLOY_PRIME_URL yarn build:example && cp -r exampleSite/public ../repo"

[context.branch-deploy.environment]
  HUGO_GOOGLEANALYTICS = "dev"